### ISSUE TITLE
Simbody 3.5 release todo list

### ISSUE THREAD

**Issue by sherm1** [simbody/simbody#275]
- [x] update changelog (and convert it to markdown)
- [x] write CONTRIBUTING.md
- [x] in README.md, replace "3.4" with "3.5" (PR #291)
- [x] check that README.md is up to date
- [x] read through tutorial, fix links and text as needed
- [x] update version number for advanced user's manual
- [x] check theory manual
- [x] post doxygen on simtk.org
- [x] get José's blessing on the debian subdirectory 
- [x] make 3.5 branch
- [x] make 3.5 release (tag)
- [x] delete 3.3 branch
- [x] update master branch to 3.6
- [x] announce release on forum
